"""Client for the e-signature provider.

Documenso (self-hosted, https://docs.documenso.com/developers/public-api)
is used for real when APP_DOCUMENSO_API_URL and APP_DOCUMENSO_API_TOKEN are
set: the contract PDF is uploaded, a signature field is placed for the
signer, and Documenso emails them a signing link. Its DOCUMENT_COMPLETED
webhook (POST /webhooks/documenso) then marks the contract signed, and the
sealed PDF is fetched back from Documenso for download.

With no provider configured (the default dev/demo stack) request_signature
returns a deterministic simulated reference instead, and signing is
completed by POST /webhooks/esign or the demo-only sign-simulated route.

Provider references:
  documenso-doc-<id>    a real Documenso document
  <provider>-ref-<hash> simulated, nothing was sent anywhere
"""
import hashlib
import logging
import re
from typing import Optional

import httpx

from app.config import settings

logger = logging.getLogger(__name__)

DOCUMENSO_REF_PREFIX = "documenso-doc-"
_TIMEOUT = httpx.Timeout(30.0)


class EsignProviderError(Exception):
    pass


def documenso_enabled() -> bool:
    return bool(settings.documenso_api_url and settings.documenso_api_token)


def documenso_document_id(provider_ref: Optional[str]) -> Optional[str]:
    if provider_ref and provider_ref.startswith(DOCUMENSO_REF_PREFIX):
        return provider_ref[len(DOCUMENSO_REF_PREFIX):]
    return None


def _simulated_ref(contract_id: str, signer_email: Optional[str], provider: str) -> str:
    digest = hashlib.sha256(f"esign:{provider}:{contract_id}:{signer_email or ''}".encode()).hexdigest()[:16]
    return f"{provider}-ref-{digest}"


def _pdf_page_count(pdf: bytes) -> int:
    return max(1, len(re.findall(rb"/Type\s*/Page(?![s\w])", pdf)))


def _documenso_client() -> httpx.AsyncClient:
    return httpx.AsyncClient(
        base_url=settings.documenso_api_url.rstrip("/"),
        headers={"Authorization": settings.documenso_api_token},
        timeout=_TIMEOUT,
    )


async def _documenso_send(contract_id: str, signer_email: str, pdf: bytes, title: str) -> str:
    async with _documenso_client() as client:
        created = await client.post("/api/v1/documents", json={
            "title": title,
            "externalId": contract_id,
            "recipients": [{"name": signer_email, "email": signer_email, "role": "SIGNER"}],
            "meta": {
                "subject": f"Please sign: {title}",
                "message": "This contract was generated by the IT Procurement Intelligence Platform.",
            },
        })
        if created.status_code >= 400:
            raise EsignProviderError(f"Documenso create document failed ({created.status_code}): {created.text[:300]}")
        body = created.json()
        document_id = body["documentId"]
        recipient_id = body["recipients"][0]["recipientId"]

        # The upload URL is a pre-signed storage URL, not the API host, so
        # it must not carry the API token.
        async with httpx.AsyncClient(timeout=_TIMEOUT) as storage:
            uploaded = await storage.put(body["uploadUrl"], content=pdf, headers={"Content-Type": "application/pdf"})
        if uploaded.status_code >= 400:
            raise EsignProviderError(f"Documenso PDF upload failed ({uploaded.status_code})")

        # Signature field on the last page, over the "For the Company"
        # signature line that contract_pdf draws. Positions are percentages.
        field = await client.post(f"/api/v1/documents/{document_id}/fields", json={
            "recipientId": recipient_id,
            "type": "SIGNATURE",
            "pageNumber": _pdf_page_count(pdf),
            "pageX": 9, "pageY": 70, "pageWidth": 36, "pageHeight": 6,
        })
        if field.status_code >= 400:
            raise EsignProviderError(f"Documenso add signature field failed ({field.status_code}): {field.text[:300]}")

        sent = await client.post(f"/api/v1/documents/{document_id}/send", json={"sendEmail": True})
        if sent.status_code >= 400:
            raise EsignProviderError(f"Documenso send failed ({sent.status_code}): {sent.text[:300]}")

    logger.info(f"Contract {contract_id} sent to Documenso as document {document_id}")
    return f"{DOCUMENSO_REF_PREFIX}{document_id}"


async def request_signature(
    contract_id: str,
    signer_email: Optional[str],
    provider: str = "documenso",
    pdf: Optional[bytes] = None,
    title: str = "Contract",
) -> str:
    """Routes the contract for signature and returns the provider reference."""
    p_name = (provider or "documenso").strip().lower()
    if p_name == "documenso" and documenso_enabled():
        if not signer_email:
            raise EsignProviderError("a signer email is required to send through Documenso")
        if not pdf:
            raise EsignProviderError("no contract PDF to send")
        return await _documenso_send(contract_id, signer_email, pdf, title)
    return _simulated_ref(contract_id, signer_email, p_name)


async def download_signed_pdf(provider_ref: Optional[str]) -> Optional[bytes]:
    """The provider's sealed PDF for a completed Documenso document, or
    None when the contract wasn't signed through a live Documenso."""
    document_id = documenso_document_id(provider_ref)
    if document_id is None or not documenso_enabled():
        return None
    async with _documenso_client() as client:
        res = await client.get(f"/api/v1/documents/{document_id}/download")
        if res.status_code >= 400:
            raise EsignProviderError(f"Documenso download failed ({res.status_code}): {res.text[:300]}")
        download_url = res.json()["downloadUrl"]
    async with httpx.AsyncClient(timeout=_TIMEOUT) as storage:
        pdf = await storage.get(download_url)
    if pdf.status_code >= 400:
        raise EsignProviderError(f"Documenso signed PDF fetch failed ({pdf.status_code})")
    return pdf.content
